# 容器测试 brokek B的配置文件
server:
  group: test_podman
  brokerName: test_podman-broker-b
  port: 6779
etcd:
  endpoints: ["192.168.112.130:2379"]
  dialTimoutSeconds: 10
log:
  writers:
    - id: app-default
      type: STDOUT
      level: INFO
    - id: common-error
      type: STDERR
      level: ERROR
  loggers:
    - name: app-logger
      writers: ["app-default", "common-error"]
