server:
  group: test_podman
  brokerName: test_podman-broker
  port: 6777
etcd:
  endpoints: ["localhost:2379"]
  dialTimoutSeconds: 10
log:
  writers:
    - id: app-default
      type: STDOUT
      level: INFO
    - id: common-error
      type: STDERR
      level: ERROR
  loggers:
    - name: app-logger
      writers: ["app-default", "common-error"]
