@startuml BrokerGroup创建

actor 管理员 as admin
database 数据库集群
database etcd 
database 消息队列元数据库 as admin_db
participant 消息队列管理系统 as mqadminsys
participant broker集群

== 数据库资源 ==

admin -> 数据库集群++: 创建数据库物理资源 
admin++
数据库集群 -> admin--: 数据库物理资源创建完成
admin -> mqadminsys++: 录入数据库资源信息

mqadminsys -> admin_db++: 信息落库
admin_db ->mqadminsys--:
mqadminsys -> admin--
admin--
== broker资源 ==
admin -> broker集群++: 发送broker机器创建请求, \n每个broker机器携带相同的broker_group标识
admin++
broker集群 -> admin--:
admin--

broker集群 -> etcd++: 创建etcd租约,基于租约机制,\n每台broker机器将ip、端口信息写入etcd\nbroker宕机时,相关机器信息会因及时未续租而被删除
broker集群++
etcd -> broker集群--:
broker集群--

== topic创建 ==

admin -> mqadminsys++: 携带broker_group,发送topic创建请求
admin++
mqadminsys -> admin_db++: 获取数据库资源信息
admin_db -> mqadminsys--:
mqadminsys -> etcd++: 获取broker_group下的所有broker信息
etcd -> mqadminsys--:
mqadminsys -> mqadminsys: 计算db库数量, 有多少db就创建多少分区,\n每个分区各一个分组
mqadminsys -> mqadminsys: 将分区平均分配给broker管理
mqadminsys -> admin_db++: 分配结果落库
admin_db -> mqadminsys--:
mqadminsys -> 数据库集群++: 执行DDL SQL, 创建消息分区表
数据库集群 -> mqadminsys--:
mqadminsys -> admin--: topic创建完成
admin--

loop watch broker全量机器信息
mqadminsys -> etcd++: watch broker
mqadminsys++
etcd --> mqadminsys--: 初次返回, 全量缓存至内存/broker变更, 增量更新缓存
mqadminsys--
end loop

== broker启动 ==
broker集群 -> mqadminsys++: grpc通信\n获取自身的队列分配信息
broker集群++
mqadminsys -> admin_db++: 查询分配信息
admin_db -> mqadminsys--:
mqadminsys -> broker集群--:
broker集群--

== MQ client启动 ==
mqclient -> mqclient: 配置参数\ntopic+broker_group
loop admin心跳

mqclient -> mqadminsys++: grpc通信\n查询topic信息\nbroker_group下的机器信息
mqclient++
mqadminsys -> mqclient--: 返回topic信息、机器信息
mqclient--
end loop

loop broker心跳

mqclient -> broker集群++: 自定义协议通信\n与每个broker建立长连接, 定时上报心跳,\n心跳报文中包含client的订阅信息与ip信息
mqclient++
broker集群 -> mqclient--:
mqclient--
end loop